// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJLyIjtiwserYZUEk6dxqSyjf8TIYtsIE',
    appId: '1:253112393593:web:0d084aaa42070fb9dc19a8',
    messagingSenderId: '253112393593',
    projectId: 'chat-app-bdf53',
    authDomain: 'chat-app-bdf53.firebaseapp.com',
    storageBucket: 'chat-app-bdf53.appspot.com',
    measurementId: 'G-BK0MW76L8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWvVNhn1KH8Zx77eWWAIxcVKJ0YWDelzQ',
    appId: '1:253112393593:android:65e941f22b35ca02dc19a8',
    messagingSenderId: '253112393593',
    projectId: 'chat-app-bdf53',
    storageBucket: 'chat-app-bdf53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj0J7Ued0Hwb-HizWgN1v1T--qOTRCi5A',
    appId: '1:253112393593:ios:e3d1a9174af0c37fdc19a8',
    messagingSenderId: '253112393593',
    projectId: 'chat-app-bdf53',
    storageBucket: 'chat-app-bdf53.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj0J7Ued0Hwb-HizWgN1v1T--qOTRCi5A',
    appId: '1:253112393593:ios:53f6bfaaf48fa799dc19a8',
    messagingSenderId: '253112393593',
    projectId: 'chat-app-bdf53',
    storageBucket: 'chat-app-bdf53.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
